"""Strategy port — interface that all trading strategies must implement."""

from typing import Protocol, runtime_checkable

from domain.events.types import DomainEvent


@runtime_checkable
class Strategy(Protocol):
    strategy_id: str

    def on_start(self, event: DomainEvent) -> None: ...
    def on_stop(self, event: DomainEvent) -> None: ...
    def on_quote(self, quote: object) -> None: ...
    def on_bar(self, bar: object) -> None: ...
    def on_fill(self, fill: object) -> None: ...
    def on_event(self, event: DomainEvent) -> None: ...
