"""Core module — domain enums, data models, result type, connection interface."""

from __future__ import annotations

from brokers.common.core.auth import (
    AuthManager,
    EnvTokenStateStore,
    JsonTokenStateStore,
    TokenSource,
    TokenState,
    TokenStateStore,
)
from brokers.common.core.constants import (
    BACKOFF_JITTER,
    BACKOFF_MULTIPLIER,
    BATCH_MAX_WORKERS,
    CIRCUIT_BREAKER_FAILURE_THRESHOLD,
    CIRCUIT_BREAKER_OPEN_DURATION_MS,
    CIRCUIT_BREAKER_SUCCESS_THRESHOLD,
    DAILY_PNL_POLL_INTERVAL_SECONDS,
    DAILY_PNL_ROLLOVER_HOUR_IST,
    DEFAULT_EXCHANGE,
    DEFAULT_EXCHANGE_SEGMENT_FALLBACK,
    DEFAULT_HISTORY_PAGE_DAYS,
    DEFAULT_HTTP_TIMEOUT_SECONDS,
    DEFAULT_LOG_LEVEL,
    DEFAULT_MAX_DAILY_DAYS,
    DEFAULT_MAX_INTRADAY_DAYS,
    DEFAULT_STOP_TIMEOUT_SECONDS,
    DEFAULT_TICK_SIZE,
    DEAD_LETTER_QUEUE_MAX_SIZE,
    DHAN_DEPTH_20_MAX_INSTRUMENTS,
    DHAN_DEPTH_200_MAX_INSTRUMENTS,
    DHAN_IDEMPOTENCY_MAX_SIZE,
    DHAN_IDEMPOTENCY_TTL_SECONDS,
    DHAN_NOTIONAL_WARNING_INR,
    DHAN_REFRESH_COOLDOWN_SECONDS,
    DHAN_TOKEN_LIFETIME_SECONDS,
    DHAN_TOKEN_REFRESH_BUFFER_SECONDS,
    DHAN_TOKEN_SCHEDULER_INTERVAL_SECONDS,
    IST_OFFSET,
    MAX_RETRY_ATTEMPTS,
    MAX_RETRY_DELAY_MS,
    MCX_CLOSE_HOUR_IST,
    MCX_CLOSE_MINUTE_IST,
    MCX_OPEN_HOUR_IST,
    MCX_OPEN_MINUTE_IST,
    MIN_SLEEP_SECONDS,
    NSE_CLOSE_HOUR_IST,
    NSE_CLOSE_MINUTE_IST,
    NSE_OPEN_HOUR_IST,
    NSE_OPEN_MINUTE_IST,
    OBSERVABILITY_DEFAULT_HOST,
    OBSERVABILITY_DEFAULT_PORT,
    PHANTOM_CAPITAL_INR,
    PROCESSED_TRADE_CLEANUP_INTERVAL_SECONDS,
    PROCESSED_TRADE_RETENTION_SECONDS,
    RECONCILIATION_INTERVAL_SECONDS,
    RETRY_BASE_DELAY_MS,
    RISK_DAILY_LOSS_PERCENT,
    RISK_GROSS_PERCENT,
    RISK_POSITION_PERCENT,
    THIRD_PARTY_LOG_LEVEL,
    TOKEN_CLOCK_SKEW_SECONDS,
    TOKEN_REFRESH_RECOMMENDED_BUFFER_SECONDS,
)
from brokers.common.core.exchange_segments import (
    is_commodity_segment,
    is_currency_segment,
    is_derivative_segment,
    is_equity_segment,
    parse_segment,
    wire_value,
    canonical_exchange_short,
)
from brokers.common.core.instruments import Instrument, InstrumentRegistry
from brokers.common.core.domain import (
    Balance,
    ConditionalAlert,
    ConditionalAlertRequest,
    DepthLevel,
    FundLimits,
    Holding,
    MarketDepth,
    MarketIntelligenceSnapshot,
    OptionContract,
    Order,
    OrderResponse,
    PnlExitPolicy,
    PnlExitResult,
    Position,
    Quote,
    Trade,
)
from brokers.common.core.pnl_calculator import PnLCalculator, PnLSnapshot
from brokers.common.core.reconciliation import (
    DriftItem,
    ReconciliationReport,
)
from brokers.common.core.requests import (
    HistoricalCandle,
    ModifyOrderRequest,
    OrderPreview,
    OrderRequest,
    SliceOrderRequest,
)
from brokers.common.core.result import GatewayResult, ResultMetadata
from brokers.common.core.types import (
    Capability,
    ConnectionStatus,
    ExchangeSegment,
    InstrumentType,
    OrderStatus,
    OrderType,
    ProductType,
    Side,
    Validity,
)

__all__ = [
    "AuthManager",
    "Balance",
    "Capability",
    "ConditionalAlert",
    "ConditionalAlertRequest",
    "ConnectionStatus",
    "DepthLevel",
    "DriftItem",
    "EnvTokenStateStore",
    "ExchangeSegment",
    "FundLimits",
    "GatewayResult",
    "HistoricalCandle",
    "Holding",
    "Instrument",
    "InstrumentRegistry",
    "InstrumentType",
    "JsonTokenStateStore",
    "MarketDepth",
    "MarketIntelligenceSnapshot",
    "ModifyOrderRequest",
    "OptionContract",
    "Order",
    "OrderPreview",
    "OrderRequest",
    "OrderResponse",
    "OrderStatus",
    "OrderType",
    "PnLCalculator",
    "PnLSnapshot",
    "PnlCalculator",
    "PnlExitPolicy",
    "PnlExitResult",
    "Position",
    "ProductType",
    "Quote",
    "ReconciliationReport",
    "ResultMetadata",
    "Side",
    "SliceOrderRequest",
    "TokenSource",
    "TokenState",
    "TokenStateStore",
    "Trade",
    "Validity",
]
