"""Capability-enum coverage surfaces."""

from domain.capabilities import Capability
from domain.capability_manifest.types import surface

CAPABILITY_ENUM_SURFACES = (
    # ── Capability-enum coverage ──
    surface(
        "capability.news",
        capability=Capability.NEWS,
        upstox="news.get_news",
        cli=(("news", "src/interface/ui/commands/news.py"),),
        notes="MCP: broker_news; services: get_news",
        tier="extended",
    ),
    surface(
        "capability.market_status",
        capability=Capability.MARKET_STATUS,
        upstox="market_status.get_market_status",
        tier="broker_only",
        broker_only_reason="Upstox adapter only",
        severity_if_gap="P3",
    ),
    surface(
        "capability.order_stream",
        capability=Capability.ORDER_STREAM,
        gateway_method="stream_order",
        dhan="order_stream.connect",
        cli=(("websocket", "src/interface/ui/commands/websocket.py"),),
        tier="extended",
        notes="CLI reports connection status only",
    ),
    surface(
        "capability.idempotency",
        capability=Capability.IDEMPOTENCY,
        dhan="orders",
        upstox="idempotency_cache",
        tier="broker_only",
        broker_only_reason="Internal OMS/broker cache",
        severity_if_gap="P3",
    ),
    surface(
        "capability.multi_order",
        capability=Capability.MULTI_ORDER,
        upstox="order_client.place_multi_order",
        cli=(("place-orders", "src/interface/ui/commands/order_placement.py"),),
        tier="extended",
    ),
    surface(
        "capability.session_risk",
        capability=Capability.SESSION_RISK,
        upstox="risk_manager",
        cli=(
            ("risk status", "src/interface/ui/commands/risk_controls.py"),
            ("oms", "src/interface/ui/commands/oms.py"),
        ),
        rest=(("GET", "/api/v1/risk/state", "src/interface/api/routers/risk.py", "oms"),),
        cli_data_source="oms",
    ),
    surface(
        "capability.smartlist",
        capability=Capability.SMARTLIST,
        upstox="intelligence.get_smartlist",
        tier="broker_only",
        broker_only_reason="Upstox intelligence adapter",
        severity_if_gap="P3",
    ),
    surface(
        "capability.fii_dii",
        capability=Capability.FII_DII,
        upstox="intelligence.get_fii_flow",
        tier="broker_only",
        broker_only_reason="Upstox intelligence adapter",
        severity_if_gap="P3",
    ),
    surface(
        "capability.oi_pcr_maxpain",
        capability=Capability.OI_PCR_MAXPAIN,
        upstox="intelligence.get_pcr",
        rest=(
            (
                "GET",
                "/api/v1/options/pcr/{underlying}",
                "src/interface/api/routers/options.py",
                "datalake",
            ),
            (
                "GET",
                "/api/v1/options/max-pain/{underlying}",
                "src/interface/api/routers/options.py",
                "datalake",
            ),
            (
                "GET",
                "/api/v1/options/volume-profile/{underlying}",
                "src/interface/api/routers/options.py",
                "datalake",
            ),
        ),
        tier="extended",
    ),
    surface(
        "capability.market_intelligence",
        capability=Capability.MARKET_INTELLIGENCE,
        upstox="intelligence.get_snapshot",
        tier="broker_only",
        broker_only_reason="Upstox intelligence bundle",
        severity_if_gap="P3",
    ),
    surface(
        "capability.tsl",
        capability=Capability.TSL,
        tier="broker_only",
        broker_only_reason="Not implemented at broker layer",
        severity_if_gap="P3",
    ),
    surface(
        "capability.mtf",
        capability=Capability.MTF,
        tier="broker_only",
        broker_only_reason="Product type only; no dedicated surface",
        severity_if_gap="P3",
    ),
    surface(
        "capability.webhooks",
        capability=Capability.WEBHOOKS,
        upstox="feed_authorizer",
        tier="broker_only",
        broker_only_reason="Upstox feed authorizer internal",
        severity_if_gap="P3",
    ),
    surface(
        "capability.amo_order",
        capability=Capability.AMO_ORDER,
        gateway_method="place_order",
        dhan="orders.place_order",
        upstox="order_command.place_order",
        tier="broker_only",
        broker_only_reason="AMO flag on standard place_order",
        severity_if_gap="P3",
    ),
    surface(
        "capability.portfolio_stream",
        capability=Capability.PORTFOLIO_STREAM,
        upstox="portfolio_stream",
        tier="broker_only",
        severity_if_gap="P3",
        notes="UpstoxPortfolioStream wired on broker init and lifecycle",
    ),
    surface(
        "capability.order_slicing",
        capability=Capability.ORDER_SLICING,
        dhan="orders.place_slice_order",
        upstox="slice.place_slice_order",
        tier="broker_only",
        broker_only_reason="Same as slice_order",
        severity_if_gap="P1",
    ),
    surface(
        "capability.depth_30",
        capability=Capability.DEPTH_30,
        gateway_method="depth",
        dhan="market_data.get_depth",
        upstox="market_data.get_depth",
        cli=(("depth", "src/interface/ui/commands/market_handlers.py"),),
        tier="broker_only",
        broker_only_reason="Uses generic depth endpoint",
        severity_if_gap="P3",
    ),
    surface(
        "capability.level2_market_data",
        capability=Capability.LEVEL2_MARKET_DATA,
        gateway_method="depth_20",
        dhan="depth_20_feed.subscribe",
        tier="extended",
        broker_only_reason="Dhan depth_20/200 feeds — no CLI command",
    ),
    surface(
        "capability.depth_20",
        capability=Capability.DEPTH_20,
        gateway_method="depth_20",
        dhan="depth_20_feed.subscribe",
        tier="extended",
        broker_only_reason="Dhan depth_20 feed — alias of level2_market_data",
    ),
    surface(
        "capability.depth_200",
        capability=Capability.DEPTH_200,
        gateway_method="depth_20",
        dhan="depth_20_feed.subscribe",
        tier="extended",
        broker_only_reason="Dhan depth_200 feed — alias of level2_market_data",
    ),
    surface(
        "capability.option_greeks",
        capability=Capability.OPTION_GREEKS,
        upstox="market_data_v3.get_option_greeks_v3",
        cli=(("option-chain", "src/interface/ui/commands/market.py"),),
        rest=(
            (
                "GET",
                "/api/v1/options/iv-surface/{underlying}",
                "src/interface/api/routers/options.py",
                "datalake",
            ),
        ),
        tier="extended",
    ),
    surface(
        "capability.global_markets",
        capability=Capability.GLOBAL_MARKETS,
        tier="broker_only",
        broker_only_reason="Not implemented",
        severity_if_gap="P3",
    ),
    surface(
        "capability.volatility_index",
        capability=Capability.VOLATILITY_INDEX,
        tier="broker_only",
        broker_only_reason="Not implemented",
        severity_if_gap="P3",
    ),
    surface(
        "capability.authenticate",
        gateway_method="authenticate",
        tier="extended",
        broker_only_reason="Internal broker authentication port method",
    ),
    surface(
        "capability.unstream",
        gateway_method="unstream",
        tier="extended",
        broker_only_reason="Internal broker streaming unsubscribe port method",
    ),
    surface(
        "capability.get_order",
        gateway_method="get_order",
        tier="extended",
        broker_only_reason="Internal broker order query port method",
    ),
    surface(
        "capability.list_capabilities",
        gateway_method="list_capabilities",
        tier="extended",
        broker_only_reason="Internal broker capabilities listing port method",
    ),
)
