"""Core market / streaming / batch capability surfaces."""

from domain.capabilities import Capability
from domain.capability_manifest.types import surface

CORE_SURFACES = (
    # ── Core market / streaming / batch ──
    surface(
        "market_data.history",
        capability=Capability.HISTORICAL_DATA,
        gateway_method="history",
        abc_required=True,
        dhan="historical.get_historical",
        upstox="historical.fetch_candles",
        cli=(
            ("historical", "src/interface/ui/commands/market_handlers.py"),
            ("history", "src/interface/ui/commands/market_handlers.py"),
            ("history", "src/brokers/cli/broker.py"),
        ),
        rest=(
            ("GET", "/api/v1/market/candles", "src/interface/api/routers/market.py", "datalake"),
            ("GET", "/api/v1/live/candles", "src/interface/api/routers/live/market.py", "live_broker"),
        ),
        notes="Dual API + MCP broker_history; services: get_history",
    ),
    surface(
        "market_data.quote",
        capability=Capability.MARKET_DATA,
        gateway_method="quote",
        abc_required=True,
        dhan="market_data.get_quote",
        upstox="market_data.get_quote",
        cli=(
            ("quote", "src/interface/ui/commands/market_handlers.py"),
            ("quote", "src/brokers/cli/broker.py"),
        ),
        notes="MCP: broker_quote; services: get_quote",
        rest=(
            ("GET", "/api/v1/market/quote/{symbol}", "src/interface/api/routers/market.py", "datalake"),
            ("GET", "/api/v1/live/quote/{symbol}", "src/interface/api/routers/live/market.py", "live_broker"),
        ),
    ),
    surface(
        "market_data.ltp",
        capability=Capability.MARKET_DATA,
        gateway_method="ltp",
        abc_required=True,
        dhan="market_data.get_ltp",
        upstox="market_data.get_ltp",
        rest=(("GET", "/api/v1/live/ltp/{symbol}", "src/interface/api/routers/live/market.py", "live_broker"),),
        notes="No dedicated CLI/REST; used internally by dashboard/validate",
    ),
    surface(
        "market_data.depth",
        capability=Capability.DEPTH,
        gateway_method="depth",
        abc_required=True,
        dhan="market_data.get_depth",
        upstox="market_data.get_depth",
        cli=(
            ("depth", "src/interface/ui/commands/market_handlers.py"),
            ("depth", "src/brokers/cli/broker.py"),
        ),
        rest=(("GET", "/api/v1/live/depth/{symbol}", "src/interface/api/routers/live/market.py", "live_broker"),),
        notes="MCP: broker_market_depth; services: get_depth, probe_depth_ws",
    ),
    surface(
        "derivatives.option_chain",
        capability=Capability.OPTIONS_CHAIN,
        gateway_method="option_chain",
        abc_required=True,
        dhan="options.get_option_chain",
        upstox="options.get_option_chain",
        cli=(("option-chain", "src/interface/ui/commands/market_handlers.py"),),
        rest=(
            ("GET", "/api/v1/options/chain/{underlying}", "src/interface/api/routers/options.py", "datalake"),
            (
                "GET",
                "/api/v1/live/options/chain/{underlying}",
                "src/interface/api/routers/live/derivatives.py",
                "live_broker",
            ),
        ),
    ),
    surface(
        "derivatives.future_chain",
        capability=Capability.FUTURES,
        gateway_method="future_chain",
        abc_required=True,
        dhan="futures.get_contracts",
        upstox="futures.get_contracts",
        cli=(("futures", "src/interface/ui/commands/market_handlers.py"),),
        rest=(
            (
                "GET",
                "/api/v1/live/futures/chain/{underlying}",
                "src/interface/api/routers/live/derivatives.py",
                "live_broker",
            ),
        ),
    ),
    surface(
        "streaming.websocket",
        capability=Capability.WEBSOCKET,
        gateway_method="stream",
        abc_required=True,
        dhan="market_feed.subscribe",
        upstox="market_data_websocket.subscribe",
        cli=(
            ("stream", "src/interface/ui/commands/market.py"),
            ("websocket", "src/interface/ui/commands/websocket.py"),
        ),
        rest=(
            ("WS", "/ws/market", "src/interface/api/ws/market.py", "live_broker"),
            ("WS", "/ws/market/{symbol}", "src/interface/api/ws/market.py", "live_broker"),
        ),
    ),
    surface(
        "streaming.depth_stream",
        capability=Capability.DEPTH,
        gateway_method="stream_depth",
        abc_required=True,
        dhan="gateway.stream_depth",
        upstox="market_data.subscribe_depth",
        cli=(("depth", "src/interface/ui/commands/market_handlers.py"),),
        rest=(("WS", "/ws/market/depth/{symbol}", "src/interface/api/ws/market.py", "live_broker"),),
    ),
    surface(
        "batch.ltp_batch",
        capability=Capability.MARKET_DATA,
        gateway_method="ltp_batch",
        abc_required=True,
        dhan="market_data.get_batch_ltp",
        upstox="market_data.get_ltp",
        tier="broker_only",
        broker_only_reason="Batch API used internally; no user-facing surface",
        severity_if_gap="P3",
    ),
    surface(
        "batch.quote_batch",
        capability=Capability.MARKET_DATA,
        gateway_method="quote_batch",
        abc_required=True,
        dhan="market_data.get_batch_quote",
        upstox="market_data.get_quote",
        tier="broker_only",
        broker_only_reason="Batch API used internally",
        severity_if_gap="P3",
    ),
    surface(
        "batch.history_batch",
        capability=Capability.HISTORICAL_DATA,
        gateway_method="history_batch",
        abc_required=True,
        dhan="historical.get_historical",
        upstox="historical.fetch_history_batch",
        tier="broker_only",
        broker_only_reason="Batch API used internally",
        severity_if_gap="P3",
    ),
)
