"""Extended broker feature capability surfaces."""

from domain.capabilities import Capability
from domain.capability_manifest.types import surface

EXTENDED_SURFACES = (
    # ── Extended broker features ──
    surface(
        "extended.user_profile",
        gateway_method="extended.get_user_profile",
        extended_only=True,
        dhan="user_profile.get_profile",
        upstox="portfolio.get_profile",
        cli=(("profile", "src/interface/ui/commands/extended_orders.py"),),
        rest=(("GET", "/api/v1/live/profile", "src/interface/api/routers/live/extended.py", "live_broker"),),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.super_orders",
        gateway_method="extended.place_super_order",
        extended_only=True,
        dhan="super_orders.place_super_order",
        cli=(("super-order", "src/interface/ui/commands/extended_orders.py"),),
        notes="services: list_super_orders; MCP: via broker extended when wired",
        rest=(
            ("POST", "/api/v1/live/orders/super", "src/interface/api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.forever_orders",
        gateway_method="extended.place_forever_order",
        extended_only=True,
        dhan="forever_orders.place_forever_order",
        upstox="gtt.place_forever_order",
        cli=(("forever-order", "src/interface/ui/commands/extended_orders.py"),),
        notes="services: list_forever_orders",
        rest=(
            ("POST", "/api/v1/live/orders/forever", "src/interface/api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.conditional_triggers",
        capability=Capability.ALERTS,
        gateway_method="extended.place_conditional_trigger",
        extended_only=True,
        dhan="conditional_triggers.place_trigger",
        upstox="gtt.place_alert",
        cli=(("trigger", "src/interface/ui/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/alerts/trigger", "src/interface/api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.margin",
        capability=Capability.MARGIN,
        extended_only=True,
        dhan="margin.calculate",
        upstox="margin.calculate_margin",
        cli=(("margin", "src/interface/ui/commands/extended_orders.py"),),
        rest=(
            (
                "POST",
                "/api/v1/live/margin/calculate",
                "src/interface/api/routers/live/extended.py",
                "live_broker",
            ),
        ),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.exit_all",
        capability=Capability.EXIT_ALL,
        gateway_method="extended.exit_all",
        extended_only=True,
        dhan="exit_all.exit_all",
        upstox="exit_all.exit_all",
        cli=(("exit-all", "src/interface/ui/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/orders/exit-all", "src/interface/api/routers/live/extended.py", "live_broker"),
            ("POST", "/api/v1/portfolio/square-off", "src/interface/api/routers/portfolio.py", "oms"),
        ),
        severity_if_gap="P1",
    ),
    surface(
        "extended.ledger",
        gateway_method="extended.get_ledger",
        extended_only=True,
        dhan="ledger.get_ledger",
        upstox="portfolio.get_ledger",
        cli=(("ledger", "src/interface/ui/commands/extended_orders.py"),),
        rest=(("GET", "/api/v1/live/ledger", "src/interface/api/routers/live/extended.py", "live_broker"),),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.edis",
        gateway_method="extended.authorize_edis",
        extended_only=True,
        dhan="edis.authorize_edis",
        cli=(("edis", "src/interface/ui/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/edis/authorize", "src/interface/api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.ip_management",
        capability=Capability.STATIC_IP,
        gateway_method="extended.set_ip",
        extended_only=True,
        dhan="ip_management.set_ip",
        upstox="static_ip.set_static_ip",
        cli=(("ip", "src/interface/ui/commands/extended_orders.py"),),
        rest=(
            ("GET", "/api/v1/live/ip", "src/interface/api/routers/live/extended.py", "live_broker"),
            ("POST", "/api/v1/live/ip", "src/interface/api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.gtt_order",
        capability=Capability.GTT_ORDER,
        extended_only=True,
        upstox="gtt.place_gtt_order",
        cli=(("gtt-order", "src/interface/ui/commands/extended_orders.py"),),
        rest=(("POST", "/api/v1/live/orders/gtt", "src/interface/api/routers/live/extended.py", "live_broker"),),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.cover_order",
        capability=Capability.COVER_ORDER,
        extended_only=True,
        upstox="cover.place_cover_order",
        cli=(("cover-order", "src/interface/ui/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/orders/cover", "src/interface/api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.slice_order",
        capability=Capability.SLICE_ORDER,
        extended_only=True,
        dhan="orders.place_slice_order",
        upstox="slice.place_slice_order",
        cli=(("slice-order", "src/interface/ui/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/orders/slice", "src/interface/api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.kill_switch_broker",
        capability=Capability.KILL_SWITCH,
        extended_only=True,
        dhan="orders.kill_switch",
        upstox="kill_switch.set_status",
        cli=(("risk kill-switch", "src/interface/ui/commands/risk_controls.py"),),
        rest=(("POST", "/api/v1/risk/kill-switch", "src/interface/api/routers/risk.py", "oms"),),
        cli_data_source="oms",
        severity_if_gap="P1",
        notes="CLI/REST use OMS kill-switch, not broker-native kill switch",
    ),
    surface(
        "extended.ipo",
        capability=Capability.IPO,
        gateway_method="extended.get_ipos",
        extended_only=True,
        upstox="ipo.get_ipos",
        cli=(("ipo", "src/interface/ui/commands/extended_orders.py"),),
        rest=(("GET", "/api/v1/live/ipo", "src/interface/api/routers/live/extended.py", "live_broker"),),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.mutual_funds",
        capability=Capability.MUTUAL_FUNDS,
        gateway_method="extended.place_mutual_fund_order",
        extended_only=True,
        upstox="mutual_funds.place_order",
        cli=(("mf", "src/interface/ui/commands/extended_orders.py"),),
        rest=(
            ("GET", "/api/v1/live/mutual-funds", "src/interface/api/routers/live/extended.py", "live_broker"),
            ("POST", "/api/v1/live/mutual-funds", "src/interface/api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.payments",
        capability=Capability.PAYMENTS,
        gateway_method="extended.initiate_payout",
        extended_only=True,
        upstox="payments.initiate_payout",
        cli=(("payout", "src/interface/ui/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/payments/payout", "src/interface/api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.fundamentals",
        capability=Capability.FUNDAMENTALS,
        gateway_method="extended.get_pnl",
        extended_only=True,
        upstox="fundamentals.get_pnl",
        cli=(("fundamentals", "src/interface/ui/commands/extended_orders.py"),),
        rest=(
            (
                "GET",
                "/api/v1/live/fundamentals/{isin}",
                "src/interface/api/routers/live/extended.py",
                "live_broker",
            ),
        ),
        tier="extended",
        broker_only_reason="Upstox fundamentals API",
        severity_if_gap="P3",
    ),
)
