"""Orders / portfolio / instruments / lifecycle capability surfaces."""

from domain.capabilities import Capability
from domain.capability_manifest.types import surface

ORDER_SURFACES = (
    # ── Orders / portfolio / instruments / lifecycle ──
    surface(
        "orders.place",
        capability=Capability.ORDER_COMMAND,
        gateway_method="place_order",
        abc_required=True,
        dhan="orders.place_order",
        upstox="order_command.place_order",
        cli=(
            ("place-order", "src/interface/ui/commands/order_placement.py"),
            ("place-orders", "src/interface/ui/commands/order_placement.py"),
            ("bracket-order", "src/interface/ui/commands/order_composition.py"),
            ("oco-order", "src/interface/ui/commands/order_composition.py"),
            ("basket-order", "src/interface/ui/commands/order_composition.py"),
        ),
        rest=(("POST", "/api/v1/orders", "src/interface/api/routers/orders.py", "live_broker"),),
        cli_data_source="oms",
        severity_if_gap="P1",
    ),
    surface(
        "orders.cancel",
        capability=Capability.ORDER_COMMAND,
        gateway_method="cancel_order",
        abc_required=True,
        dhan="orders.cancel_order",
        upstox="order_command.cancel_order",
        cli=(("cancel-order", "src/interface/ui/commands/order_placement.py"),),
        rest=(("DELETE", "/api/v1/orders/{order_id}", "src/interface/api/routers/orders.py", "live_broker"),),
        cli_data_source="oms",
        severity_if_gap="P1",
    ),
    surface(
        "orders.modify",
        capability=Capability.ORDER_COMMAND,
        gateway_method="modify_order",
        dhan="orders.modify_order",
        upstox="order_command.modify_order",
        cli=(("modify-order", "src/interface/ui/commands/order_placement.py"),),
        rest=(("PUT", "/api/v1/orders/{order_id}", "src/interface/api/routers/orders.py", "live_broker"),),
        severity_if_gap="P1",
    ),
    surface(
        "orders.query_orderbook",
        capability=Capability.ORDER_QUERY,
        gateway_method="get_orderbook",
        abc_required=True,
        dhan="orders.get_orderbook",
        upstox="order_query.get_order_list",
        cli=(
            ("orders", "src/interface/ui/commands/oms.py"),
            ("oms", "src/interface/ui/commands/oms.py"),
        ),
        rest=(
            ("GET", "/api/v1/orders", "src/interface/api/routers/orders.py", "oms"),
            ("GET", "/api/v1/orders/{order_id}", "src/interface/api/routers/orders.py", "oms"),
            ("GET", "/api/v1/live/orders", "src/interface/api/routers/live/orders.py", "live_broker"),
        ),
        notes="REST OMS routes coexist with /live/orders broker orderbook",
    ),
    surface(
        "orders.query_trades",
        capability=Capability.HISTORICAL_TRADES,
        gateway_method="get_trade_book",
        abc_required=True,
        dhan="orders.get_trade_book",
        upstox="order_query.get_trades",
        cli=(("trades", "src/interface/ui/commands/oms.py"),),
        rest=(
            ("GET", "/api/v1/orders/trades", "src/interface/api/routers/orders.py", "oms"),
            ("GET", "/api/v1/orders/tradebook", "src/interface/api/routers/orders.py", "oms"),
            ("GET", "/api/v1/live/trades", "src/interface/api/routers/live/orders.py", "live_broker"),
        ),
    ),
    surface(
        "portfolio.positions",
        capability=Capability.PORTFOLIO,
        gateway_method="positions",
        abc_required=True,
        dhan="portfolio.get_positions",
        upstox="portfolio.get_positions",
        cli=(("positions", "src/interface/ui/commands/portfolio.py"),),
        rest=(
            ("GET", "/api/v1/portfolio/positions", "src/interface/api/routers/portfolio.py", "oms"),
            ("GET", "/api/v1/live/positions", "src/interface/api/routers/live/portfolio.py", "live_broker"),
        ),
    ),
    surface(
        "portfolio.holdings",
        capability=Capability.PORTFOLIO,
        gateway_method="holdings",
        abc_required=True,
        dhan="portfolio.get_holdings",
        upstox="portfolio.get_holdings",
        cli=(("holdings", "src/interface/ui/commands/portfolio.py"),),
        rest=(
            ("GET", "/api/v1/portfolio/holdings", "src/interface/api/routers/portfolio.py", "oms"),
            ("GET", "/api/v1/live/holdings", "src/interface/api/routers/live/portfolio.py", "live_broker"),
        ),
    ),
    surface(
        "portfolio.funds",
        capability=Capability.PORTFOLIO,
        gateway_method="funds",
        abc_required=True,
        dhan="portfolio.get_balance",
        upstox="portfolio.get_balance",
        cli=(
            ("account", "src/interface/ui/commands/account.py"),
            ("funds", "src/interface/ui/commands/account.py"),
        ),
        rest=(("GET", "/api/v1/live/funds", "src/interface/api/routers/live/portfolio.py", "live_broker"),),
    ),
    surface(
        "portfolio.trades_alias",
        capability=Capability.HISTORICAL_TRADES,
        gateway_method="trades",
        abc_required=True,
        dhan="orders.get_trade_book",
        upstox="order_query.get_trades",
        cli=(("trades", "src/interface/ui/commands/oms.py"),),
        severity_if_gap="P3",
        notes="Alias for get_trade_book on gateway ABC",
    ),
    surface(
        "instruments.search",
        capability=Capability.INSTRUMENT_SEARCH,
        gateway_method="search",
        abc_required=True,
        dhan="resolver",
        upstox="instrument_resolver.search",
        cli=(
            ("search", "src/interface/ui/commands/search.py"),
            ("instruments lookup", "src/interface/ui/commands/instruments.py"),
        ),
        rest=(("GET", "/api/v1/symbols/search", "src/interface/api/routers/symbols.py", "datalake"),),
    ),
    surface(
        "instruments.load",
        capability=Capability.INSTRUMENTS,
        gateway_method="load_instruments",
        abc_required=True,
        dhan="load_instruments",
        upstox="instrument_loader.load",
        cli=(("instruments stats", "src/interface/ui/commands/instruments.py"),),
        tier="broker_only",
        broker_only_reason="Startup/bootstrap only",
        severity_if_gap="P3",
    ),
    surface(
        "lifecycle.capabilities",
        gateway_method="capabilities",
        abc_required=True,
        cli=(
            ("doctor", "src/interface/ui/commands/doctor/strategies/active_broker.py"),
            ("capability", "src/brokers/cli/broker.py"),
        ),
        notes="MCP: broker_capabilities; services: get_capabilities",
        tier="broker_only",
        broker_only_reason="Metadata; doctor reports flags",
        severity_if_gap="P3",
    ),
    surface(
        "lifecycle.describe",
        gateway_method="describe",
        abc_required=True,
        cli=(("broker", "src/interface/ui/commands/broker.py"),),
        tier="broker_only",
        severity_if_gap="P3",
    ),
    surface(
        "lifecycle.close",
        gateway_method="close",
        abc_required=True,
        dhan="close",
        upstox="disconnect",
        tier="broker_only",
        broker_only_reason="Lifecycle teardown",
        severity_if_gap="P3",
    ),
)
