"""Declarative capability catalog (coverage SSOT).

Data only — types and query helpers live in sibling modules.
"""

from __future__ import annotations

from domain.capabilities import Capability
from domain.capability_manifest.types import surface

CAPABILITY_SURFACES = (
    # ── Core market / streaming / batch ──
    surface(
        "market_data.history",
        capability=Capability.HISTORICAL_DATA,
        gateway_method="history",
        abc_required=True,
        dhan="historical.get_historical",
        upstox="historical.fetch_candles",
        cli=(
            ("historical", "cli/commands/market_handlers.py"),
            ("history", "cli/commands/market_handlers.py"),
        ),
        rest=(
            ("GET", "/api/v1/market/candles", "api/routers/market.py", "datalake"),
            ("GET", "/api/v1/live/candles", "api/routers/live/market.py", "live_broker"),
        ),
        notes="Dual API: datalake candles + /live/candles broker history",
    ),
    surface(
        "market_data.quote",
        capability=Capability.MARKET_DATA,
        gateway_method="quote",
        abc_required=True,
        dhan="market_data.get_quote",
        upstox="market_data.get_quote",
        cli=(("quote", "cli/commands/market_handlers.py"),),
        rest=(
            ("GET", "/api/v1/market/quote/{symbol}", "api/routers/market.py", "datalake"),
            ("GET", "/api/v1/live/quote/{symbol}", "api/routers/live/market.py", "live_broker"),
        ),
    ),
    surface(
        "market_data.ltp",
        capability=Capability.MARKET_DATA,
        gateway_method="ltp",
        abc_required=True,
        dhan="market_data.get_ltp",
        upstox="market_data.get_ltp",
        rest=(("GET", "/api/v1/live/ltp/{symbol}", "api/routers/live/market.py", "live_broker"),),
        notes="No dedicated CLI/REST; used internally by dashboard/validate",
    ),
    surface(
        "market_data.depth",
        capability=Capability.DEPTH,
        gateway_method="depth",
        abc_required=True,
        dhan="market_data.get_depth",
        upstox="market_data.get_depth",
        cli=(("depth", "cli/commands/market_handlers.py"),),
        rest=(("GET", "/api/v1/live/depth/{symbol}", "api/routers/live/market.py", "live_broker"),),
    ),
    surface(
        "derivatives.option_chain",
        capability=Capability.OPTIONS_CHAIN,
        gateway_method="option_chain",
        abc_required=True,
        dhan="options.get_option_chain",
        upstox="options.get_option_chain",
        cli=(("option-chain", "cli/commands/market_handlers.py"),),
        rest=(
            ("GET", "/api/v1/options/chain/{underlying}", "api/routers/options.py", "datalake"),
            (
                "GET",
                "/api/v1/live/options/chain/{underlying}",
                "api/routers/live/derivatives.py",
                "live_broker",
            ),
        ),
    ),
    surface(
        "derivatives.future_chain",
        capability=Capability.FUTURES,
        gateway_method="future_chain",
        abc_required=True,
        dhan="futures.get_contracts",
        upstox="futures.get_contracts",
        cli=(("futures", "cli/commands/market_handlers.py"),),
        rest=(
            (
                "GET",
                "/api/v1/live/futures/chain/{underlying}",
                "api/routers/live/derivatives.py",
                "live_broker",
            ),
        ),
    ),
    surface(
        "streaming.websocket",
        capability=Capability.WEBSOCKET,
        gateway_method="stream",
        abc_required=True,
        dhan="market_feed.subscribe",
        upstox="market_data_websocket.subscribe",
        cli=(
            ("stream", "cli/commands/market.py"),
            ("websocket", "cli/commands/websocket.py"),
        ),
        rest=(
            ("WS", "/ws/market", "api/ws/market.py", "live_broker"),
            ("WS", "/ws/market/{symbol}", "api/ws/market.py", "live_broker"),
        ),
    ),
    surface(
        "streaming.depth_stream",
        capability=Capability.DEPTH,
        gateway_method="stream_depth",
        abc_required=True,
        dhan="gateway.stream_depth",
        upstox="market_data.subscribe_depth",
        cli=(("depth", "cli/commands/market_handlers.py"),),
        rest=(("WS", "/ws/market/depth/{symbol}", "api/ws/market.py", "live_broker"),),
    ),
    surface(
        "batch.ltp_batch",
        capability=Capability.MARKET_DATA,
        gateway_method="ltp_batch",
        abc_required=True,
        dhan="market_data.get_batch_ltp",
        upstox="market_data.get_ltp",
        tier="broker_only",
        broker_only_reason="Batch API used internally; no user-facing surface",
        severity_if_gap="P3",
    ),
    surface(
        "batch.quote_batch",
        capability=Capability.MARKET_DATA,
        gateway_method="quote_batch",
        abc_required=True,
        dhan="market_data.get_batch_quote",
        upstox="market_data.get_quote",
        tier="broker_only",
        broker_only_reason="Batch API used internally",
        severity_if_gap="P3",
    ),
    surface(
        "batch.history_batch",
        capability=Capability.HISTORICAL_DATA,
        gateway_method="history_batch",
        abc_required=True,
        dhan="historical.get_historical",
        upstox="historical.fetch_history_batch",
        tier="broker_only",
        broker_only_reason="Batch API used internally",
        severity_if_gap="P3",
    ),
    # ── Orders / portfolio / instruments / lifecycle ──
    surface(
        "orders.place",
        capability=Capability.ORDER_COMMAND,
        gateway_method="place_order",
        abc_required=True,
        dhan="orders.place_order",
        upstox="order_command.place_order",
        cli=(
            ("place-order", "cli/commands/order_placement.py"),
            ("place-orders", "cli/commands/order_placement.py"),
            ("bracket-order", "cli/commands/order_composition.py"),
            ("oco-order", "cli/commands/order_composition.py"),
            ("basket-order", "cli/commands/order_composition.py"),
        ),
        rest=(("POST", "/api/v1/orders", "api/routers/orders.py", "live_broker"),),
        cli_data_source="oms",
        severity_if_gap="P1",
    ),
    surface(
        "orders.cancel",
        capability=Capability.ORDER_COMMAND,
        gateway_method="cancel_order",
        abc_required=True,
        dhan="orders.cancel_order",
        upstox="order_command.cancel_order",
        cli=(("cancel-order", "cli/commands/order_placement.py"),),
        rest=(("DELETE", "/api/v1/orders/{order_id}", "api/routers/orders.py", "live_broker"),),
        cli_data_source="oms",
        severity_if_gap="P1",
    ),
    surface(
        "orders.modify",
        capability=Capability.ORDER_COMMAND,
        gateway_method="modify_order",
        dhan="orders.modify_order",
        upstox="order_command.modify_order",
        cli=(("modify-order", "cli/commands/order_placement.py"),),
        rest=(("PUT", "/api/v1/orders/{order_id}", "api/routers/orders.py", "live_broker"),),
        severity_if_gap="P1",
    ),
    surface(
        "orders.query_orderbook",
        capability=Capability.ORDER_QUERY,
        gateway_method="get_orderbook",
        abc_required=True,
        dhan="orders.get_orderbook",
        upstox="order_query.get_order_list",
        cli=(
            ("orders", "cli/commands/oms.py"),
            ("oms", "cli/commands/oms.py"),
        ),
        rest=(
            ("GET", "/api/v1/orders", "api/routers/orders.py", "oms"),
            ("GET", "/api/v1/orders/{order_id}", "api/routers/orders.py", "oms"),
            ("GET", "/api/v1/live/orders", "api/routers/live/orders.py", "live_broker"),
        ),
        notes="REST OMS routes coexist with /live/orders broker orderbook",
    ),
    surface(
        "orders.query_trades",
        capability=Capability.HISTORICAL_TRADES,
        gateway_method="get_trade_book",
        abc_required=True,
        dhan="orders.get_trade_book",
        upstox="order_query.get_trades",
        cli=(("trades", "cli/commands/oms.py"),),
        rest=(
            ("GET", "/api/v1/orders/trades", "api/routers/orders.py", "oms"),
            ("GET", "/api/v1/orders/tradebook", "api/routers/orders.py", "oms"),
            ("GET", "/api/v1/live/trades", "api/routers/live/orders.py", "live_broker"),
        ),
    ),
    surface(
        "portfolio.positions",
        capability=Capability.PORTFOLIO,
        gateway_method="positions",
        abc_required=True,
        dhan="portfolio.get_positions",
        upstox="portfolio.get_positions",
        cli=(("positions", "cli/commands/portfolio.py"),),
        rest=(
            ("GET", "/api/v1/portfolio/positions", "api/routers/portfolio.py", "oms"),
            ("GET", "/api/v1/live/positions", "api/routers/live/portfolio.py", "live_broker"),
        ),
    ),
    surface(
        "portfolio.holdings",
        capability=Capability.PORTFOLIO,
        gateway_method="holdings",
        abc_required=True,
        dhan="portfolio.get_holdings",
        upstox="portfolio.get_holdings",
        cli=(("holdings", "cli/commands/portfolio.py"),),
        rest=(
            ("GET", "/api/v1/portfolio/holdings", "api/routers/portfolio.py", "oms"),
            ("GET", "/api/v1/live/holdings", "api/routers/live/portfolio.py", "live_broker"),
        ),
    ),
    surface(
        "portfolio.funds",
        capability=Capability.PORTFOLIO,
        gateway_method="funds",
        abc_required=True,
        dhan="portfolio.get_balance",
        upstox="portfolio.get_balance",
        cli=(
            ("account", "cli/commands/account.py"),
            ("funds", "cli/commands/account.py"),
        ),
        rest=(("GET", "/api/v1/live/funds", "api/routers/live/portfolio.py", "live_broker"),),
    ),
    surface(
        "portfolio.trades_alias",
        capability=Capability.HISTORICAL_TRADES,
        gateway_method="trades",
        abc_required=True,
        dhan="orders.get_trade_book",
        upstox="order_query.get_trades",
        cli=(("trades", "cli/commands/oms.py"),),
        severity_if_gap="P3",
        notes="Alias for get_trade_book on gateway ABC",
    ),
    surface(
        "instruments.search",
        capability=Capability.INSTRUMENT_SEARCH,
        gateway_method="search",
        abc_required=True,
        dhan="resolver",
        upstox="instrument_resolver.search",
        cli=(
            ("search", "cli/commands/search.py"),
            ("instruments lookup", "cli/commands/instruments.py"),
        ),
        rest=(("GET", "/api/v1/symbols/search", "api/routers/symbols.py", "datalake"),),
    ),
    surface(
        "instruments.load",
        capability=Capability.INSTRUMENTS,
        gateway_method="load_instruments",
        abc_required=True,
        dhan="load_instruments",
        upstox="instrument_loader.load",
        cli=(("instruments stats", "cli/commands/instruments.py"),),
        tier="broker_only",
        broker_only_reason="Startup/bootstrap only",
        severity_if_gap="P3",
    ),
    surface(
        "lifecycle.capabilities",
        gateway_method="capabilities",
        abc_required=True,
        cli=(("doctor", "cli/commands/doctor/strategies/active_broker.py"),),
        tier="broker_only",
        broker_only_reason="Metadata; doctor reports flags",
        severity_if_gap="P3",
    ),
    surface(
        "lifecycle.describe",
        gateway_method="describe",
        abc_required=True,
        cli=(("broker", "cli/commands/broker.py"),),
        tier="broker_only",
        severity_if_gap="P3",
    ),
    surface(
        "lifecycle.close",
        gateway_method="close",
        abc_required=True,
        dhan="close",
        upstox="disconnect",
        tier="broker_only",
        broker_only_reason="Lifecycle teardown",
        severity_if_gap="P3",
    ),
    # ── Extended broker features ──
    surface(
        "extended.user_profile",
        gateway_method="extended.get_user_profile",
        extended_only=True,
        dhan="user_profile.get_profile",
        upstox="portfolio.get_profile",
        cli=(("profile", "cli/commands/extended_orders.py"),),
        rest=(("GET", "/api/v1/live/profile", "api/routers/live/extended.py", "live_broker"),),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.super_orders",
        gateway_method="extended.place_super_order",
        extended_only=True,
        dhan="super_orders.place_super_order",
        cli=(("super-order", "cli/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/orders/super", "api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.forever_orders",
        gateway_method="extended.place_forever_order",
        extended_only=True,
        dhan="forever_orders.place_forever_order",
        upstox="gtt.place_forever_order",
        cli=(("forever-order", "cli/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/orders/forever", "api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.conditional_triggers",
        capability=Capability.ALERTS,
        gateway_method="extended.place_conditional_trigger",
        extended_only=True,
        dhan="conditional_triggers.place_trigger",
        upstox="gtt.place_alert",
        cli=(("trigger", "cli/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/alerts/trigger", "api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.margin",
        capability=Capability.MARGIN,
        extended_only=True,
        dhan="margin.calculate",
        upstox="margin.calculate_margin",
        cli=(("margin", "cli/commands/extended_orders.py"),),
        rest=(
            (
                "POST",
                "/api/v1/live/margin/calculate",
                "api/routers/live/extended.py",
                "live_broker",
            ),
        ),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.exit_all",
        capability=Capability.EXIT_ALL,
        gateway_method="extended.exit_all",
        extended_only=True,
        dhan="exit_all.exit_all",
        upstox="exit_all.exit_all",
        cli=(("exit-all", "cli/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/orders/exit-all", "api/routers/live/extended.py", "live_broker"),
            ("POST", "/api/v1/portfolio/square-off", "api/routers/portfolio.py", "oms"),
        ),
        severity_if_gap="P1",
    ),
    surface(
        "extended.ledger",
        gateway_method="extended.get_ledger",
        extended_only=True,
        dhan="ledger.get_ledger",
        upstox="portfolio.get_ledger",
        cli=(("ledger", "cli/commands/extended_orders.py"),),
        rest=(("GET", "/api/v1/live/ledger", "api/routers/live/extended.py", "live_broker"),),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.edis",
        gateway_method="extended.authorize_edis",
        extended_only=True,
        dhan="edis.authorize_edis",
        cli=(("edis", "cli/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/edis/authorize", "api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.ip_management",
        capability=Capability.STATIC_IP,
        gateway_method="extended.set_ip",
        extended_only=True,
        dhan="ip_management.set_ip",
        upstox="static_ip.set_static_ip",
        cli=(("ip", "cli/commands/extended_orders.py"),),
        rest=(
            ("GET", "/api/v1/live/ip", "api/routers/live/extended.py", "live_broker"),
            ("POST", "/api/v1/live/ip", "api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.gtt_order",
        capability=Capability.GTT_ORDER,
        extended_only=True,
        upstox="gtt.place_gtt_order",
        cli=(("gtt-order", "cli/commands/extended_orders.py"),),
        rest=(("POST", "/api/v1/live/orders/gtt", "api/routers/live/extended.py", "live_broker"),),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.cover_order",
        capability=Capability.COVER_ORDER,
        extended_only=True,
        upstox="cover.place_cover_order",
        cli=(("cover-order", "cli/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/orders/cover", "api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.slice_order",
        capability=Capability.SLICE_ORDER,
        extended_only=True,
        dhan="orders.place_slice_order",
        upstox="slice.place_slice_order",
        cli=(("slice-order", "cli/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/orders/slice", "api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P1",
    ),
    surface(
        "extended.kill_switch_broker",
        capability=Capability.KILL_SWITCH,
        extended_only=True,
        dhan="orders.kill_switch",
        upstox="kill_switch.set_status",
        cli=(("risk kill-switch", "cli/commands/risk_controls.py"),),
        rest=(("POST", "/api/v1/risk/kill-switch", "api/routers/risk.py", "oms"),),
        cli_data_source="oms",
        severity_if_gap="P1",
        notes="CLI/REST use OMS kill-switch, not broker-native kill switch",
    ),
    surface(
        "extended.ipo",
        capability=Capability.IPO,
        gateway_method="extended.get_ipos",
        extended_only=True,
        upstox="ipo.get_ipos",
        cli=(("ipo", "cli/commands/extended_orders.py"),),
        rest=(("GET", "/api/v1/live/ipo", "api/routers/live/extended.py", "live_broker"),),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.mutual_funds",
        capability=Capability.MUTUAL_FUNDS,
        gateway_method="extended.place_mutual_fund_order",
        extended_only=True,
        upstox="mutual_funds.place_order",
        cli=(("mf", "cli/commands/extended_orders.py"),),
        rest=(
            ("GET", "/api/v1/live/mutual-funds", "api/routers/live/extended.py", "live_broker"),
            ("POST", "/api/v1/live/mutual-funds", "api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.payments",
        capability=Capability.PAYMENTS,
        gateway_method="extended.initiate_payout",
        extended_only=True,
        upstox="payments.initiate_payout",
        cli=(("payout", "cli/commands/extended_orders.py"),),
        rest=(
            ("POST", "/api/v1/live/payments/payout", "api/routers/live/extended.py", "live_broker"),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "extended.fundamentals",
        capability=Capability.FUNDAMENTALS,
        gateway_method="extended.get_pnl",
        extended_only=True,
        upstox="fundamentals.get_pnl",
        cli=(("fundamentals", "cli/commands/extended_orders.py"),),
        rest=(
            (
                "GET",
                "/api/v1/live/fundamentals/{isin}",
                "api/routers/live/extended.py",
                "live_broker",
            ),
        ),
        tier="extended",
        broker_only_reason="Upstox fundamentals API",
        severity_if_gap="P3",
    ),
    # ── Capability-enum coverage ──
    surface(
        "capability.news",
        capability=Capability.NEWS,
        upstox="news.get_news",
        cli=(("news", "cli/commands/news.py"),),
        tier="extended",
    ),
    surface(
        "capability.market_status",
        capability=Capability.MARKET_STATUS,
        upstox="market_status.get_market_status",
        tier="broker_only",
        broker_only_reason="Upstox adapter only",
        severity_if_gap="P3",
    ),
    surface(
        "capability.order_stream",
        capability=Capability.ORDER_STREAM,
        gateway_method="stream_order",
        dhan="order_stream.connect",
        cli=(("websocket", "cli/commands/websocket.py"),),
        tier="extended",
        notes="CLI reports connection status only",
    ),
    surface(
        "capability.idempotency",
        capability=Capability.IDEMPOTENCY,
        dhan="orders",
        upstox="idempotency_cache",
        tier="broker_only",
        broker_only_reason="Internal OMS/broker cache",
        severity_if_gap="P3",
    ),
    surface(
        "capability.multi_order",
        capability=Capability.MULTI_ORDER,
        upstox="order_client.place_multi_order",
        cli=(("place-orders", "cli/commands/order_placement.py"),),
        tier="extended",
    ),
    surface(
        "capability.session_risk",
        capability=Capability.SESSION_RISK,
        upstox="risk_manager",
        cli=(
            ("risk status", "cli/commands/risk_controls.py"),
            ("oms", "cli/commands/oms.py"),
        ),
        rest=(("GET", "/api/v1/risk/state", "api/routers/risk.py", "oms"),),
        cli_data_source="oms",
    ),
    surface(
        "capability.smartlist",
        capability=Capability.SMARTLIST,
        upstox="intelligence.get_smartlist",
        tier="broker_only",
        broker_only_reason="Upstox intelligence adapter",
        severity_if_gap="P3",
    ),
    surface(
        "capability.fii_dii",
        capability=Capability.FII_DII,
        upstox="intelligence.get_fii_flow",
        tier="broker_only",
        broker_only_reason="Upstox intelligence adapter",
        severity_if_gap="P3",
    ),
    surface(
        "capability.oi_pcr_maxpain",
        capability=Capability.OI_PCR_MAXPAIN,
        upstox="intelligence.get_pcr",
        rest=(
            ("GET", "/api/v1/options/pcr/{underlying}", "api/routers/options.py", "datalake"),
            ("GET", "/api/v1/options/max-pain/{underlying}", "api/routers/options.py", "datalake"),
            (
                "GET",
                "/api/v1/options/volume-profile/{underlying}",
                "api/routers/options.py",
                "datalake",
            ),
        ),
        tier="extended",
    ),
    surface(
        "capability.market_intelligence",
        capability=Capability.MARKET_INTELLIGENCE,
        upstox="intelligence.get_snapshot",
        tier="broker_only",
        broker_only_reason="Upstox intelligence bundle",
        severity_if_gap="P3",
    ),
    surface(
        "capability.tsl",
        capability=Capability.TSL,
        tier="broker_only",
        broker_only_reason="Not implemented at broker layer",
        severity_if_gap="P3",
    ),
    surface(
        "capability.mtf",
        capability=Capability.MTF,
        tier="broker_only",
        broker_only_reason="Product type only; no dedicated surface",
        severity_if_gap="P3",
    ),
    surface(
        "capability.webhooks",
        capability=Capability.WEBHOOKS,
        upstox="feed_authorizer",
        tier="broker_only",
        broker_only_reason="Upstox feed authorizer internal",
        severity_if_gap="P3",
    ),
    surface(
        "capability.amo_order",
        capability=Capability.AMO_ORDER,
        gateway_method="place_order",
        dhan="orders.place_order",
        upstox="order_command.place_order",
        tier="broker_only",
        broker_only_reason="AMO flag on standard place_order",
        severity_if_gap="P3",
    ),
    surface(
        "capability.portfolio_stream",
        capability=Capability.PORTFOLIO_STREAM,
        upstox="portfolio_stream",
        tier="broker_only",
        severity_if_gap="P3",
        notes="UpstoxPortfolioStream wired on broker init and lifecycle",
    ),
    surface(
        "capability.order_slicing",
        capability=Capability.ORDER_SLICING,
        dhan="orders.place_slice_order",
        upstox="slice.place_slice_order",
        tier="broker_only",
        broker_only_reason="Same as slice_order",
        severity_if_gap="P1",
    ),
    surface(
        "capability.depth_30",
        capability=Capability.DEPTH_30,
        gateway_method="depth",
        dhan="market_data.get_depth",
        upstox="market_data.get_depth",
        cli=(("depth", "cli/commands/market_handlers.py"),),
        tier="broker_only",
        broker_only_reason="Uses generic depth endpoint",
        severity_if_gap="P3",
    ),
    surface(
        "capability.level2_market_data",
        capability=Capability.LEVEL2_MARKET_DATA,
        gateway_method="depth_20",
        dhan="depth_20_feed.subscribe",
        tier="extended",
        broker_only_reason="Dhan depth_20/200 feeds — no CLI command",
    ),
    surface(
        "capability.depth_20",
        capability=Capability.DEPTH_20,
        gateway_method="depth_20",
        dhan="depth_20_feed.subscribe",
        tier="extended",
        broker_only_reason="Dhan depth_20 feed — alias of level2_market_data",
    ),
    surface(
        "capability.option_greeks",
        capability=Capability.OPTION_GREEKS,
        upstox="market_data_v3.get_option_greeks_v3",
        cli=(("option-chain", "cli/commands/market.py"),),
        rest=(
            (
                "GET",
                "/api/v1/options/iv-surface/{underlying}",
                "api/routers/options.py",
                "datalake",
            ),
        ),
        tier="extended",
    ),
    surface(
        "capability.global_markets",
        capability=Capability.GLOBAL_MARKETS,
        tier="broker_only",
        broker_only_reason="Not implemented",
        severity_if_gap="P3",
    ),
    surface(
        "capability.volatility_index",
        capability=Capability.VOLATILITY_INDEX,
        tier="broker_only",
        broker_only_reason="Not implemented",
        severity_if_gap="P3",
    ),
    # ── Monitoring / health ──
    surface(
        "monitoring.api_health",
        cli=(("doctor", "cli/commands/doctor/__init__.py"),),
        rest=(
            ("GET", "/api/v1/health", "api/routers/health.py", "none"),
            ("GET", "/api/v1/health/readyz", "api/routers/health.py", "none"),
            ("GET", "/api/v1/health/metrics", "api/routers/health.py", "oms"),
            ("GET", "/api/v1/health/metrics/prometheus", "api/routers/health.py", "none"),
        ),
    ),
    surface(
        "monitoring.live_broker_health",
        cli=(("doctor", "cli/commands/doctor/__init__.py"),),
        rest=(
            ("GET", "/api/v1/live/health", "api/routers/live/health.py", "live_broker"),
            ("GET", "/api/v1/live/readyz", "api/routers/live/health.py", "live_broker"),
            ("GET", "/api/v1/live/capabilities", "api/routers/live/health.py", "live_broker"),
        ),
    ),
    # ── API product surfaces ──
    surface(
        "api.scanner",
        cli=(("analytics scan", "cli/commands/analytics_scanner.py"),),
        rest=(
            ("GET", "/api/v1/scanner/results", "api/routers/scanner.py", "datalake"),
            ("GET", "/api/v1/scanner/top-candidates", "api/routers/scanner.py", "datalake"),
            ("GET", "/api/v1/scanner/snapshots", "api/routers/scanner.py", "datalake"),
            ("POST", "/api/v1/scanner/run", "api/routers/scanner.py", "mixed"),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "api.backtest",
        cli=(("analytics backtest", "cli/commands/analytics_backtest.py"),),
        rest=(
            ("POST", "/api/v1/backtest/run", "api/routers/backtest.py", "datalake"),
            (
                "GET",
                "/api/v1/backtest/results/{backtest_id}",
                "api/routers/backtest.py",
                "datalake",
            ),
            ("GET", "/api/v1/backtest/comparison/{run_id}", "api/routers/backtest.py", "datalake"),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "api.replay",
        cli=(("analytics replay", "cli/commands/analytics_replay.py"),),
        rest=(
            ("GET", "/api/v1/replay/sessions", "api/routers/replay.py", "datalake"),
            ("POST", "/api/v1/replay/sessions", "api/routers/replay.py", "datalake"),
            ("GET", "/api/v1/replay/sessions/{session_id}", "api/routers/replay.py", "datalake"),
            (
                "POST",
                "/api/v1/replay/sessions/{session_id}/play",
                "api/routers/replay.py",
                "datalake",
            ),
            (
                "POST",
                "/api/v1/replay/sessions/{session_id}/pause",
                "api/routers/replay.py",
                "datalake",
            ),
            (
                "POST",
                "/api/v1/replay/sessions/{session_id}/stop",
                "api/routers/replay.py",
                "datalake",
            ),
            (
                "POST",
                "/api/v1/replay/sessions/{session_id}/speed",
                "api/routers/replay.py",
                "datalake",
            ),
            (
                "POST",
                "/api/v1/replay/sessions/{session_id}/seek",
                "api/routers/replay.py",
                "datalake",
            ),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "api.analytics",
        cli=(("analytics breadth", "cli/commands/analytics.py"),),
        rest=(
            ("GET", "/api/v1/analytics/market-breadth", "api/routers/analytics.py", "datalake"),
            ("GET", "/api/v1/analytics/indicators", "api/routers/analytics.py", "datalake"),
            ("GET", "/api/v1/scanner/snapshots", "api/routers/scanner.py", "datalake"),
            ("GET", "/api/v1/scanner/top-candidates", "api/routers/scanner.py", "datalake"),
            ("GET", "/api/v1/analytics/relative-strength", "api/routers/analytics.py", "datalake"),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
    surface(
        "api.portfolio_summary",
        capability=Capability.PORTFOLIO,
        cli=(("oms", "cli/commands/oms.py"),),
        rest=(
            ("GET", "/api/v1/portfolio/summary", "api/routers/portfolio.py", "oms"),
            ("GET", "/api/v1/portfolio/pnl", "api/routers/portfolio.py", "oms"),
        ),
        tier="extended",
    ),
    surface(
        "api.symbols",
        capability=Capability.INSTRUMENTS,
        cli=(("instrument", "cli/commands/instrument_info.py"),),
        rest=(
            ("GET", "/api/v1/symbols/{symbol}", "api/routers/symbols.py", "datalake"),
            ("GET", "/api/v1/symbols/universe/{name}", "api/routers/symbols.py", "datalake"),
        ),
    ),
    surface(
        "api.strategy",
        cli=(("analytics strategies", "cli/commands/analytics_strategies.py"),),
        rest=(
            ("GET", "/api/v1/strategy/signals", "api/routers/strategy.py", "datalake"),
            ("GET", "/api/v1/strategy/candidates", "api/routers/strategy.py", "datalake"),
            ("GET", "/api/v1/analytics/strategies", "api/routers/analytics.py", "datalake"),
            ("POST", "/api/v1/analytics/strategies/run", "api/routers/analytics.py", "datalake"),
        ),
        tier="extended",
        severity_if_gap="P3",
    ),
)
