"""Brokers services — shared core for SDK, CLI, MCP, and startup self-test.

Every public capability has exactly one implementation here; front-ends delegate.
"""

from __future__ import annotations

from brokers.services.core import (
    cancel_order,
    extensions_from_session,
    get_capabilities,
    get_depth,
    get_depth30,
    get_funds,
    get_history,
    get_history_batch,
    get_holdings,
    get_news,
    get_option_chain,
    get_orders,
    get_positions,
    get_quote,
    lookup_instrument,
    lookup_security,
    lookup_symbol,
    list_forever_orders,
    list_super_orders,
    modify_order,
    place_order,
    probe_depth_ws,
    run_benchmark,
    run_certify,
    run_connect,
    run_diagnose,
    run_doctor,
    run_health,
    run_mapping,
    run_market_hours,
    run_subscribe_probe,
    run_verify,
    safe_serialize,
    status_from_session,
)

__all__ = [
    "cancel_order",
    "extensions_from_session",
    "get_capabilities",
    "get_depth",
    "get_depth30",
    "get_funds",
    "get_history",
    "get_history_batch",
    "get_holdings",
    "get_news",
    "get_option_chain",
    "get_orders",
    "get_positions",
    "get_quote",
    "lookup_instrument",
    "lookup_security",
    "lookup_symbol",
    "list_forever_orders",
    "list_super_orders",
    "modify_order",
    "place_order",
    "probe_depth_ws",
    "run_benchmark",
    "run_certify",
    "run_connect",
    "run_diagnose",
    "run_doctor",
    "run_health",
    "run_mapping",
    "run_market_hours",
    "run_subscribe_probe",
    "run_verify",
    "safe_serialize",
    "status_from_session",
]
