"""Broker API contracts and SPI definitions."""

from __future__ import annotations

from brokers.common.api.ports import (
    BracketOrderProvider,
    ConditionalAlertProvider,
    CoverOrderProvider,
    FuturesProvider,
    GttOrderProvider,
    IdempotencyCachePort,
    InstrumentResolver,
    MarginProvider,
    MarketDataListener,
    MarketDataProvider,
    MarketStatusProvider,
    NewsProvider,
    OptionsProvider,
    OrderBookSnapshotProvider,
    OrderCommand,
    OrderQuery,
    OrderUpdateListener,
    PortfolioProvider,
    SessionRiskProvider,
    SliceOrderCommand,
)
from brokers.common.api.spi import (
    BrokerDescriptor,
    BrokerProvider,
    BrokerRegistry,
    BrokerSource,
    CapabilityMetadata,
    CapabilityMetadataEntry,
    descriptor_from_capabilities,
)

__all__ = [
    "BracketOrderProvider",
    "BrokerDescriptor",
    "BrokerProvider",
    "BrokerRegistry",
    "BrokerSource",
    "CapabilityMetadata",
    "CapabilityMetadataEntry",
    "ConditionalAlertProvider",
    "CoverOrderProvider",
    "FuturesProvider",
    "GttOrderProvider",
    "IdempotencyCachePort",
    "InstrumentResolver",
    "MarginProvider",
    "MarketDataListener",
    "MarketDataProvider",
    "MarketStatusProvider",
    "NewsProvider",
    "OptionsProvider",
    "OrderBookSnapshotProvider",
    "OrderCommand",
    "OrderQuery",
    "OrderUpdateListener",
    "PortfolioProvider",
    "SessionRiskProvider",
    "SliceOrderCommand",
    "descriptor_from_capabilities",
]
