"""BrokerAdapter protocol — order execution, account, market data, lifecycle.

Covers the full surface every gateway (Dhan/Upstox/Paper) actually implements
and application code may call, so consumers can depend on this Protocol
instead of duck-typing against a concrete gateway class. Streaming
(``stream``/``unstream``/``stream_order``) is deliberately NOT included here —
Paper doesn't implement it, so it isn't a universal part of the contract;
check ``capabilities()`` or the concrete gateway type for streaming support.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol, runtime_checkable

from domain.commands import PlaceOrderCommand
from domain.entities import Account, Bar, Instrument, MarketDepth, Order, Position, Quote
from domain.ports.types import BrokerSnapshot
from domain.value_objects import InstrumentId, OrderId, Price, TimeFrame


@runtime_checkable
class BrokerAdapter(Protocol):
    # Lifecycle
    def connect(self) -> None: ...
    def authenticate(self) -> bool: ...
    def close(self) -> None: ...

    # Orders
    def submit_order(self, command: PlaceOrderCommand) -> OrderId: ...
    def cancel_order(self, order_id: OrderId) -> None: ...
    def modify_order(self, order_id: OrderId, command: PlaceOrderCommand) -> None: ...
    def get_order(self, order_id: OrderId) -> Order: ...
    def get_orderbook(self) -> list[Order]: ...

    # Portfolio
    def get_positions(self) -> list[Position]: ...
    def get_holdings(self) -> list[Position]: ...
    def get_funds(self) -> Account: ...
    def mass_status(self) -> BrokerSnapshot: ...

    # Market data
    def get_quote(self, instrument_id: InstrumentId) -> Quote: ...
    def ltp(self, instrument_id: InstrumentId) -> Price: ...
    def depth(self, instrument_id: InstrumentId) -> MarketDepth: ...
    def history(
        self, instrument_id: InstrumentId, timeframe: TimeFrame, start: datetime, end: datetime
    ) -> list[Bar]: ...

    # Instruments
    def load_instruments(self) -> None: ...
    def search(self, query: str) -> list[Instrument]: ...

    # Capabilities — return type is broker-plugin-defined (BrokerCapabilities
    # lives in plugins/, not domain/ — domain must not import plugins).
    def capabilities(self) -> Any: ...
