"""BrokerAdapter protocol — order execution and account queries."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from domain.commands import PlaceOrderCommand
from domain.entities import Account, Order, Position
from domain.ports.types import BrokerSnapshot
from domain.value_objects import OrderId


@runtime_checkable
class BrokerAdapter(Protocol):
    def submit_order(self, command: PlaceOrderCommand) -> OrderId: ...
    def cancel_order(self, order_id: OrderId) -> None: ...
    def modify_order(self, order_id: OrderId, command: PlaceOrderCommand) -> None: ...
    def get_order(self, order_id: OrderId) -> Order: ...
    def get_orderbook(self) -> list[Order]: ...
    def get_positions(self) -> list[Position]: ...
    def get_funds(self) -> Account: ...
    def mass_status(self) -> BrokerSnapshot: ...
